#!/usr/bin/env bash
set -e

# https://stackoverflow.com/questions/2412450/git-pre-commit-hook-changed-added-files
git diff --cached --name-status | while read state file; do
        echo "file: ${file}"
        if [[ "${file}" == "data/assets_vfsdata.go" ]]; then
            echo "Piracy is bad, mmmkay? Unstaging file: ${file}"
            git reset -- "${file}"
            exit 1
        fi
done
